const CONFIG = {
    titleWeb: "xinloiklydangghetvl",
    introTitle: 'klyxinhdep',
    introDesc: `hok biết đã làm gì nma xin lỗi kly xinh đẹp mà ghét vãi =)))👊`,
    btnIntro: '^^tự nhiên hok rep ngta😡^^',
    title: 'kly ko ghét tloc nữa',
    desc: ' ghét là bị ăn đấm👊 ',
    btnYes: 'được thoai',
    btnNo: 'ko',
    question: 'lần sau bị gì nói anh biết zứi 😇I am always be your side👊',
    btnReply: 'ghét em vãi 👊',
    reply: 'được thoai ko nói ko được',
    mess: 'anh code kqua ròi em điền cái gì cũng z =)))',
    messDesc: 'mốt anh về Bà Rịa cho kly đỡ chán nha🌷.',
    btnAccept: 'dám nói ko hok 😏',
    messLink: 'https://www.facebook.com/kahlyy' 
